SELECT 
    kcu.TABLE_NAME, 
    kcu.COLUMN_NAME, 
    kcu.CONSTRAINT_NAME, 
    kcu.REFERENCED_TABLE_NAME, 
    kcu.REFERENCED_COLUMN_NAME, 
    rc.DELETE_RULE
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS rc
    ON kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA
    AND kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
WHERE 
    kcu.TABLE_SCHEMA = 'toms' 
    AND kcu.TABLE_NAME = 'subcategories';
